## Setup and  Import

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings

In [15]:
raw_df = pd.read_csv("ai_productivity_dataset_final.csv")
raw_df

,task_id,client,project_id,client_tier,team,task_type,seniority,task_complexity_score,brief_quality_score,deadline_pressure,...,revenue,cost,profit,created_by,updated_at,task_status,workflow_stage,jira_ticket,legacy_ai_flag,content_version
0,T00000,Client_F,P038,mid,Content,report,junior,2,3.0,high,...,498.11,346.17,151.94,user_096,2025-11-28,review,finalized,JIRA-49014,true,v1
1,T00001,Client_H,P028,low,Paid Media,release,junior,1,2.0,medium,...,847.01,343.18,503.83,user_058,2026-01-26,delivered,client_review,JIRA-84793,false,v1
2,T00002,Client_D,P009,low,Design,dev,junior,3,4.0,medium,...,1374.07,365.02,1009.05,user_074,2025-09-17,in_progress,qa,JIRA-42485,true,v2
3,T00003,Client_E,P023,mid,Content,design,mid,3,2.0,low,...,2379.11,1514.73,864.38,user_011,2025-11-12,in_progress,briefing,JIRA-53111,false,v1
4,T00004,Client_C,P014,low,Design,article,senior,2,5.0,low,...,709.95,335.27,374.68,user_007,2026-05-09,review,execution,JIRA-86006,true,v2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3243,T02060,Client_F,P056,mid,SEO,report,mid,2,3.0,high,...,688.97,807.57,-118.60,user_101,2025-12-31,in_progress,briefing,JIRA-90491,true,v1
3244,T02295,Client_K,P001,low,SEO,report,mid,1,2.0,high,...,570.64,671.72,-101.08,user_096,2026-03-05,in_progress,briefing,JIRA-19154,true,v3
3245,T02652,Client_C,P027,mid,Content,dev,junior,4,3.0,medium,...,1419.09,1303.74,115.35,user_080,2025-11-20,in_progress,execution,JIRA-32851,true,v4
3246,T01915,Client_F,P016,mid,SEO,ticket,mid,3,3.0,medium,...,285.28,273.58,11.70,user_011,2026-01-08,review,client_review,NaN,false,v1
3247,T01359,Client_A,P047,high,SEO,design,mid,2,3.0,low,...,1196.58,769.59,426.99,user_096,2026-03-01,delivered,qa,JIRA-39958,false,v3

In [28]:
raw_df["task_id"].value_counts()

task_id
T00010    2
T00139    2
T00170    2
T00205    2
T00219    2
         ..
T03195    1
T03196    1
T03197    1
T03198    1
T03199    1
Name: count, Length: 3200, dtype: int64

In [ ]:
# lista di quali task_id si ripetono due volte
task_id_counts = raw_df["task_id"].value_counts()
task_id_repeated = task_id_counts[task_id_counts == 2].index.tolist()
task_id_repeated

['T00010',
 'T00139',
 'T00170',
 'T00205',
 'T00219',
 'T00285',
 'T00343',
 'T00413',
 'T00460',
 'T00608',
 'T00617',
 'T00675',
 'T00721',
 'T00726',
 'T00748',
 'T00759',
 'T00875',
 'T00881',
 'T00885',
 'T01075',
 'T01080',
 'T01148',
 'T01151',
 'T01162',
 'T01236',
 'T01344',
 'T01359',
 'T01400',
 'T01476',
 'T01516',
 'T01740',
 'T01849',
 'T01852',
 'T01881',
 'T01915',
 'T01988',
 'T02060',
 'T02075',
 'T02118',
 'T02191',
 'T02295',
 'T02307',
 'T02344',
 'T02652',
 'T02689',
 'T02958',
 'T03121',
 'T03155']

In [ ]:
#Righe di task_id filtrate per "T00010"
raw_df[raw_df["task_id"] == "T02307"]

#Verifica che ogni task_id di task_id_repeated appartenga allo stesso client 
for task_id in task_id_repeated:
    client_ids = raw_df[raw_df["task_id"] == task_id]["client"].unique()
    if len(client_ids) > 1:
        print(f"Task ID {task_id} belongs to multiple clients: {client_ids}")

Task ID T00010 belongs to multiple clients: <StringArray>
['Client_F', 'Client_J']
Length: 2, dtype: str
Task ID T00726 belongs to multiple clients: <StringArray>
['Client_[', 'Client_F']
Length: 2, dtype: str
Task ID T00875 belongs to multiple clients: <StringArray>
['Client_C', 'Client_W']
Length: 2, dtype: str
Task ID T01080 belongs to multiple clients: <StringArray>
['Client_D', 'Client_M']
Length: 2, dtype: str
Task ID T01740 belongs to multiple clients: <StringArray>
['Client_A', 'Client_S']
Length: 2, dtype: str
Task ID T02295 belongs to multiple clients: <StringArray>
['Client_W', 'Client_K']
Length: 2, dtype: str

In [ ]:
#Copia del dataframe raw_df e filtro per tenere solo le righe con i task_id_repeated che hanno lo stesso client
filtered_df = raw_df[raw_df["task_id"].isin(task_id_repeated)]
filtered_df = filtered_df.groupby("task_id").filter(lambda x: x["client"].nunique() == 1)
filtered_df

#Ordiniamo per task_id
filtered_df = filtered_df.sort_values(by="task_id")
filtered_df

,task_id,client,project_id,client_tier,team,task_type,seniority,task_complexity_score,brief_quality_score,deadline_pressure,...,revenue,cost,profit,created_by,updated_at,task_status,workflow_stage,jira_ticket,legacy_ai_flag,content_version
139,T00139,Client_H,P053,mid,Media,ad,senior,4,1.0,high,...,1130.56,919.75,210.81,user_011,2026-03-04,in_progress,briefing,JIRA-21055,true,v1
3202,T00139,Client_H,P053,mid,Media,ad,senior,4,1.0,high,...,1130.56,919.75,210.81,user_059,2026-03-05,delivered,execution,JIRA-92895,false,v4
170,T00170,Client_H,P044,high,MEDIA,report,mid,1,4.0,medium,...,795.16,1048.97,-253.81,user_003,2025-09-10,in_progress,execution,JIRA-59955,true,v3
3237,T00170,Client_H,P044,high,Media,Report,mid,1,4.0,medium,...,795.16,1048.97,-253.81,user_026,2025-09-14,review,briefing,JIRA-56374,false,v1
3240,T00205,Client_G,P017,high,SEO,ad_task,junior,2,3.0,medium,...,959.50,376.33,583.17,user_040,2026-01-06,draft,execution,JIRA-88330,false,final
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2958,T02958,Client_A,P024,low,Media,ticket,senior,4,4.0,low,...,391.42,508.89,-117.47,user_012,2025-12-19,delivered,execution,JIRA-92701,true,v1
3212,T03121,Client_B,P030,high,Media,ad,senior,2,4.0,low,...,802.60,968.81,-166.21,user_027,2025-10-01,in_progress,finalized,JIRA-22527,true,v3
3121,T03121,Client_B,P030,high,Media,paid_ad,senior,2,4.0,low,...,802.60,968.81,-166.21,user_011,2025-10-06,review,execution,NaN,true,v1
3208,T03155,Client_C,P023,high,Content,report,mid,1,1.0,low,...,930.48,465.51,464.97,user_077,2025-09-08,review,client_review,NaN,unknown,v2
3155,T03155,Client_C,P023,high,Content,report,mid,1,1.0,low,...,930.48,465.51,464.97,user_118,2025-09-07,draft,briefing,JIRA-33440,true,v2

In [ ]:
#Copia del dataframe raw_df e filtro per tenere solo le righe con i task_id_repeated e con clienti diversi
filtered_df = raw_df[raw_df["task_id"].isin(task_id_repeated)]
filtered_df = filtered_df.groupby("task_id").filter(lambda x: x["client"].nunique() > 1)
filtered_df

#Ordiniamo per task_id
filtered_df = filtered_df.sort_values(by="task_id")
filtered_df

,task_id,client,project_id,client_tier,team,task_type,seniority,task_complexity_score,brief_quality_score,deadline_pressure,...,revenue,cost,profit,created_by,updated_at,task_status,workflow_stage,jira_ticket,legacy_ai_flag,content_version
10,T00010,Client_F,P020,low,Media,ad,mid,4,3.0,low,...,743.55,756.78,-13.23,user_064,2025-09-12,delivered,client_review,JIRA-82158,false,final
3233,T00010,Client_J,P020,low,Media,ad,mid,4,3.0,low,...,743.55,756.78,-13.23,user_078,2025-09-11,in_progress,client_review,JIRA-63281,unknown,v3
726,T00726,Client_[,P050,mid,SEO,ad,mid,5,NaN,medium,...,940.09,756.98,183.11,user_038,2026-02-24,draft,client_review,JIRA-80019,unknown,v2
3204,T00726,Client_F,P050,mid,SEO,ad,mid,5,5.0,medium,...,940.09,756.98,183.11,user_069,2026-02-28,review,execution,JIRA-16744,false,v3
875,T00875,Client_C,P025,high,Media,article,junior,2,4.0,high,...,1165.00,358.52,806.48,user_044,2025-09-04,in_progress,briefing,JIRA-41694,false,v1
3220,T00875,Client_W,P025,high,Media,article,junior,2,4.0,high,...,1165.00,358.52,806.48,user_095,2025-09-02,in_progress,execution,JIRA-43065,true,v3
1080,T01080,Client_D,P006,mid,media,dev,junior,3,3.0,medium,...,470.18,475.28,-5.10,user_104,2026-02-19,in_progress,client_review,JIRA-47728,true,v1
3224,T01080,Client_M,P006,mid,Media,dev,junior,3,3.0,medium,...,470.18,475.28,-5.10,user_044,2026-02-13,delivered,execution,JIRA-70180,false,v1
1740,T01740,Client_A,P011,mid,SEO,release,junior,4,3.0,high,...,1703.55,1702.09,1.46,user_005,2026-02-12,review,briefing,JIRA-11318,true,v1
3217,T01740,Client_S,P011,mid,SEO,release,junior,4,3.0,high,...,1703.55,1702.09,1.46,user_040,2026-02-13,delivered,execution,JIRA-25057,true,v3
2295,T02295,Client_W,P001,low,SEO,report,mid,1,2.0,high,...,570.64,671.72,-101.08,user_072,2026-03-02,in_progress,briefing,JIRA-32681,true,v4
3244,T02295,Client_K,P001,low,SEO,report,mid,1,2.0,high,...,570.64,671.72,-101.08,user_096,2026-03-05,in_progress,briefing,JIRA-19154,true,v3

In [43]:
raw_df["client"].value_counts().sort_index()

client
Client_A    366
Client_B    396
Client_C    379
Client_D    384
Client_E    391
Client_F    362
Client_G    415
Client_H    392
Client_I      4
Client_J      6
Client_K     11
Client_L     13
Client_M      8
Client_N      7
Client_O      5
Client_P      6
Client_Q      8
Client_R      9
Client_S     10
Client_T     10
Client_U     10
Client_V      3
Client_W      7
Client_X      5
Client_Y      7
Client_Z     13
Client_[     12
Client_\      9
Name: count, dtype: int64

In [14]:
raw_df.info()
raw_df.shape

<class 'pandas.DataFrame'>
RangeIndex: 3248 entries, 0 to 3247
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   task_id                3248 non-null   str
 1   client                 3248 non-null   str
 2   project_id             3248 non-null   str
 3   client_tier            3248 non-null   str
 4   team                   3248 non-null   str
 5   task_type              3248 non-null   str
 6   seniority              3248 non-null   str
 7   task_complexity_score  3248 non-null   int64
 8   brief_quality_score    3179 non-null   float64
 9   deadline_pressure      3248 non-null   str
 10  scope_change_flag      3248 non-null   int64
 11  pricing_model          3248 non-null   str
 12  created_at             3248 non-null   str
 13  delivered_at           3210 non-null   str
 14  sla_days               3212 non-null   float64
 15  sla_breach             3248 non-null   int64
 16  hours_spent            3248 non-null   float64
 17  billable_hours         3166 non-null   float64
 18  ai_usage_pct           3104 non-null   float64
 19  ai_assisted            3248 non-null   bool
 20  revisions              3248 non-null   int64
 21  errors                 3248 non-null   int64
 22  rework_hours           3176 non-null   float64
 23  outcome_score          3115 non-null   float64
 24  revenue                3248 non-null   float64
 25  cost                   3248 non-null   float64
 26  profit                 3248 non-null   float64
 27  created_by             3248 non-null   str
 28  updated_at             3248 non-null   str
 29  task_status            3248 non-null   str
 30  workflow_stage         3248 non-null   str
 31  jira_ticket            2909 non-null   str
 32  legacy_ai_flag         3248 non-null   str
 33  content_version        3248 non-null   str
dtypes: bool(1), float64(10), int64(5), str(18)
memory usage: 840.7 KB

(3248, 34)

In [44]:
raw_df["project_id"].value_counts()

project_id
P028    77
P038    70
P021    64
P011    63
P060    62
        ..
P002    39
P051    39
P007    37
P048    37
P039    36
Name: count, Length: 64, dtype: int64

In [ ]:
raw_df["task_status"].value_counts()

task_status
in_progress    1129
review          866
delivered       769
draft           183
archived        151
blocked         150
Name: count, dtype: int64

In [47]:
raw_df["content_version"].value_counts()

content_version
v1       926
v2       775
v3       667
final    560
v4       320
Name: count, dtype: int64

In [48]:
raw_df["workflow_stage"].value_counts()

workflow_stage
qa               687
client_review    664
finalized        643
briefing         640
execution        614
Name: count, dtype: int64